INSERT INTO prompts (content, adult) VALUES 
('What Hitler probably called his mustache:', true),
('A lesson that probably wouldn''t be taught on Sesame Street:', false),
('Death by a thousand:', false),
('A movie that needed more nudity:', true),
('The name of a terrifying new species of spider:', false),
('Something Abe Lincoln would say during sex:', true),
('What’s the difference between planes and birds?', false),
('What NOT to say to a date while you''re on a paddle boat:', false),
('What would break up Alvin and the chipmunks', false),
('What a robot says during sex:', true),
('Worst place to have a family reunion:', false),
('The official name for the Pope''s underwear:', true),
('A good name for a dog country singer:', false),
('What is required for a orgy party?', true),
('Environmentally friendly country song:', false),
('A name for a roller derby team full of nuns:', false),
('The street name for chewable Vitamin C:', false),
('A clear sign you brought the wrong baby home from the hospital:', false),
('Name a new hillbilly cocktail:', false),
('What probably wouldn''t work as well as skis?', false),
('A bad first line for your award acceptance speech', false),
('A bad thing to say to a cashier while paying for an item', false),
('A completely wrong way to say "Applebee''s"', false),
('A fun thing to do while taking a bubble bath', false),
('A fun thing to think about', false),
('A good fake name to use when hiring for a job', false),
('A good place to hide yellow jackets', false),
('A good sign that you''re bad at playing League of Legends', false),
('A good way to get kicked out of a K-Pop concert', false),
('A great name to have on a fake driver''s license', false),
('A great new invention that starts with "Automatic"', false),
('A great opening line to start a conversation with a stranger at a party', false),
('A name for a brand of designer adult diapers', false),
('A not-very-scary name for a pirate', false),
('A prank the Supreme Court Justices probably play on each other', false),
('A rejected crayon color', false),
('A terrible name for a girl group', false),
('A rejected name for a ship in the U.S. Naval Fleet: the USS <BLANK>', false),
('A terrifying fortune cookie fortune', false),
('A Tweet from a caveman', false),
('A tourist attraction', false),
('An item on every moron''s Amazon cart', false),
('A very bad slogan for a doll franchise', false),
('Billie Eilish''s Instagram password, probably', false),
('Come up with a title for a scary version of any classic children''s movie', false),
('Come up with the name of an anime show that doesn''t exist', false),
('Fun thing to do if locked in the mall overnight', false),
('Graffiti you might find in a high school', false),
('If animals took over, an exhibit you''d see at the human zoo', false),
('If Mickey Mouse has a sense of humor, he welcomes people to Disneyland by saying, "<BLANK>!"', false),
('Jesus''s REAL last words', false),
('Little-known fact: The government allows peanut butter to contain up to 10% <BLANK>', false),
('Name a new movie starring a talking goat who is president of the United States', false),
('Name a TV drama about a vampire doctor.', false),
('Name the sequel to the game Happy Wheels if there were one. Happy Wheels 2: <BLANK>', false),
('Name your new haircutting establishment', false),
('One place a foot shouldn''t go', true),
('One thing never to do on a first date', false),
('Pants would be a whole lot better if they <BLANK>.', false),
('People wouldn''t respect He-Man as much if, to gain his power, he held up his sword and shouted <BLANK>.', false),
('Really awful basketball referees would yell "<BLANK>!"', false),
('Something that Mariah Carey would say in public every day', false),
('Schmitty: "Yes, I don''t know her. That''s her catchphrase! She doesn''t know Jennifer Lopez either! Ha ha ha ha. Alright, let''s keep going!', false),
('Something''s under my bed! AAAHHH! It''s a <BLANK>!', false),
('Something you probably shouldn''t bring on a trip to the Sahara desert', false),
('Something you shouldn''t wear to Prom', false),
('Something you’d be surprised to see while playing Fortnite', false),
('The best thing about living in a resort', false),
('The best way to get fired from The Krusty Krab', false),
('The best way to start your day before school', false),
('The crime you would commit if you could get away with it', false),
('The first commandment in the new religion you started', false),
('The most awesome Guinness World Record to break', false),
('The name of a clothing store for overweight leprechauns', false),
('The name of a font nobody would ever use', false),
('The sound a tree actually makes when it falls and no one is around to hear it', false),
('The weirdest name for a rock band', false),
('The world''s most boring game show', false),
('The worst breakfast cereal: <BLANK> Flakes', false),
('The worst Halloween costume for a young child', false),
('The worst name for a funeral home', false),
('The worst name for a guinea pig', false),
('The worst person you''d consider inviting on Thanksgiving', false),
('The worst style hamburger is <BLANK>-styled hamburgers', false),
('The worst words to say for the opening of a graduation ceremony', false),
('There''s Gryffindor, Ravenclaw, Slytherin, and Hufflepuff, but what''s the Hogwarts house few have ever heard of?', false),
('Thing you''d be most surprised to have a dentist find in your mouth', false),
('This year’s WORST Happy Meal Toy is: <BLANK>', false),
('What a moron would say at a aquarium', false),
('What kittens would say if they could talk', false),
('What to say to get out of jury duty', false),
('What you''d guess is an unadvertised ingredient in most hot dogs', false),
('Where do babies come from?', false),
('An unexpected benefit of working from home', false),
('What did that fly whisper into Pence''s ear?', false),
('Lets prank our teacher on zoom. Everybody should  <BLANK>!', false),
('WTF is my kid doing in their room all day every day?', false),
('Instead of innocent black people, Karens should be calling the cops about <BLANK>', true),
('I still have a job, but only because <BLANK>', false),
('An unknown symptom of COVID-19', false),
('What''s one thing that Trump and Biden voters can agree on?', false),
('The latest Qanon theory is that <BLANK> causes cancer', true),
('What did you learn at the BLM protest?', true),
('Scientists think that the coronavirus may have come from bats, but it actually came from <BLANK>', false),
('How to get kids excited about virtual schooling', false),
('Using only three words, describe 2020 to a waking coma patient', false),
('We should replace the police with <BLANK>', false),
('I wasn''t worried about the toilet paper shortage because <BLANK>', false),
('Kanye''s top pick for running mate', false),
('The surprising new service Amazon is rolling out during the quarantine', false),
('What would convince you to try the Russian coronavirus vaccine?', false),
('Kid Rock''s remake of "WAP" will be called "<BLANK>"', true),
('How Donald Trump actually contracted COVID-19', false),
('The only way to change a Trump voter''s mind', false),
('My COVID-19 test result just said "<BLANK>"', false),
('The best way to suppress Republican voters', false),
('What Betsy DeVos would be doing if she wasn''t rich', false),
('An existing movie title that describes 2020', false),
('Ruth Bader Ginsburg''s secret 2nd job', false),
('The Whitmer kidnappers were sponsored by <BLANK>', false),
('The best thing to pack courts with', false),
('The real reason Lindsey Graham isn''t married', false),
('The real reason Kobe''s chopper went down', false),
('What caused Mitch McConnell to be such a huge piece of shit?', true),
('Biden won''t take away your guns, but he will take away your <BLANK>', false),
('What caused 2020 to be such a shitshow?', true),
('Karens everywhere just can’t stop complaining about <BLANK>', false),
('The stupidest excuse for not attending online school:', false),
('Is there an episode code for this', false),
('The least convincing superhero power:', false),
('What you might find in a hipster''s beard:', false),
('An inappropriate slogan for a retirement home:', false),
('A dating app exclusively for clowns would be called:', false),
('The worst thing to yell in a crowded movie theater:', false),
('What never to say at a vegan potluck:', false),
('The weirdest topping to put on a pizza:', false),
('A secret you might find out about your yoga instructor:', false),
('A rejected Olympic sport: synchronized <BLANK>:', false),
('What the Statue of Liberty is really thinking:', false),
('If dogs could text, the first message they''d send would be:', false),
('A terrible theme for a children''s board game:', false),
('What would be a horrifying discovery inside a piñata?', false),
('A reality show no one would watch: "Keeping Up with the <BLANK>":', false),
('The title of an erotic movie for historians:', false),
('An awkward thing to say at a family dinner:', false),
('The most inappropriate time to start a conga line:', false),
('A terrible password for online banking:', false),
('The worst advice a doctor could give:', false),
('An unlikely candidate for the Nobel Peace Prize:', false),
('A shocking ingredient in grandma''s cookie recipe:', false),
('Something you should never do in a job interview:', false),
('What your pet would complain about if it could speak:', false),
('A terrible name for a new perfume brand:', false),
('The worst thing to find under your bed:', false),
('The least motivational gym slogan:', false),
('A surprising thing to include in a will:', false),
('A very unconventional ice cream flavor:', false),
('What not to say when meeting your in-laws for the first time:', false),
('The title of a sitcom about cannibals living together:', false),
('The most unusual college major:', false),
('A bad way to impress your date:', false),
('What aliens would say about humans after visiting Earth:', false),
('An awful prize to win in a contest:', false),
('If Shakespeare wrote a rap song, its title would be:', false),
('What you shouldn''t name your boat:', false),
('A terrible thing to say when someone passes you the salt:', false),
('What not to wear to a job interview:', false),
('The worst magic trick ever seen:', false),
('If historical figures had Twitter, what would Napoleon tweet?', false),
('What the founding fathers really meant to include in the Constitution:', false),
('The least appropriate thing to say at a funeral:', false),
('The actual reason your last relationship ended:', false),
('What the voices in your head are arguing about:', false),
('A tattoo you wouldn''t want to explain to your grandparents:', false),
('The real reason aliens won’t visit Earth:', false),
('A slogan for a brothel run by nuns:', false),
('The most scandalous title for a new reality TV show:', false),
('If hell had a welcome sign, it would say:', false),
('What not to say when your partner catches you in a lie:', false),
('A pickup line likely to get you slapped:', false),
('What not to name a racehorse:', false),
('The worst thing to shout during a golf tournament:', false),
('An inappropriate theme for a children’s birthday party:', false),
('What to put on your dating profile to guarantee no second date:', false),
('A secret you’d hate to hear from your Uber driver:', false),
('What not to say in an elevator full of strangers:', false),
('A book you’d hide when your parents visit:', false),
('The most inappropriate place to propose:', false),
('What a zombie''s dating profile might include:', false),
('The worst possible last words:', false),
('What you shouldn''t call your homemade beer:', false),
('The most inappropriate question to ask on a first date:', false),
('What you’d find in a haunted sex shop:', true),
('The worst thing to wake up and find at the foot of your bed:', false),
('The most inappropriate mascot for a children''s hospital:', false),
('A really bad name for a firework:', false),
('What you wouldn’t want to overhear in a restaurant kitchen:', false),
('The worst thing to say after kissing someone for the first time:', false)
